name: Deploy
on: [ "push" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Linting project
        run: npm run lint

      - name: Testing project
        run: npm run test
    
      - name: Deploying project
        run: npm run build
