name: Echo context data
on: 
    issues:
        types: [opened, edited, labeled]
    label:
        types: [created, deleted]
jobs:
    Echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echoing context information
              run: echo "${{ toJson(github.event) }}"
        